### PR TITLE
Make ES6-compatible

### PR DESCRIPTION
**Pull request by undecaf**
Hi, thanks for this polyfill which I just discovered! I am already using it for a Vue.js barcode scanner component.

The nullish coalescing operator (`??`) is the only non-ES6 feature in this polyfill, and it caused my current Webpack setup to fail. This may affect others as well if they expect ES6 sources. Fortunately, in this case `??` can be substituted with `||`.

### CODE REVIEW

**Comment by lekoala** [comment]
i wasn"t aware that ?? was es2020 it works fine in most modern browsers but i guess it doesn't hurt to change it :)

**Comment by undecaf** [comment]
Thanks for merging, the problem with `??` was that Babel (whichis invoked by Webpack) did not like it.

**Comment by lekoala** [comment]
@undecaf i'm using esbuild ;-) never was a big fan of webpack

**Comment by undecaf** [comment]
@lekoala I can understand that...

**Pull request merged**
